Traceback (most recent call last):
  File "c:\Users\kingp\OneDrive\Desktop\Trading_Pal-main\Gpt Trading\main.py", line 290, in query
    assistant_response = get_gpt_response(messages)
UnboundLocalError: local variable 'messages' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\kingp\OneDrive\Desktop\Trading_Pal-main\Gpt Trading\main.py", line 290, in query
    assistant_response = get_gpt_response(messages)
UnboundLocalError: local variable 'messages' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\kingp\OneDrive\Desktop\Trading_Pal-main\Gpt Trading\main.py", line 213, in query
    assistant_response = get_gpt_response(messages)
  File "c:\Users\kingp\OneDrive\Desktop\Trading_Pal-main\Gpt Trading\main.py", line 121, in get_gpt_response
    response = openai.ChatCompletion.create(
  File "C:\Users\kingp\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\kingp\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\kingp\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\kingp\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\kingp\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 667, in _interpret_response_line
    raise error.ServiceUnavailableError(
openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.
